name: hackathon_hydration
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  injectable: ^2.1.0
  google_fonts: ^4.0.4
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  go_router: ^6.5.5
  equatable: ^2.0.5
  camera: ^0.10.5+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1

  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/generated
  line_length: 80
  integrations:
    flutter_svg: true
